"""
This type stub file was generated by pyright.
"""

from typing import Callable
from ...scaffold import Scaffold

class OnUpdate(Scaffold):
    def on_update(self, filters=...) -> Callable:
        ...
    


