"""
This type stub file was generated by pyright.
"""

from typing import Union
from ...scaffold import Scaffold

class ResolveChatID(Scaffold):
    async def resolve_chat_id(self, chat_id: Union[int, str]) -> int:
        ...
    


