"""
This type stub file was generated by pyright.
"""

from typing import Optional
from ntgcalls import MediaDescription
from ...types.raw.stream import Stream

class StreamParams:
    @staticmethod
    async def get_stream_params(stream: Optional[Stream]) -> MediaDescription:
        ...
    


