"""
This type stub file was generated by pyright.
"""

from .browsers import Browsers
from .cache import Cache
from .calls import Call, CallConfig, CallData, CallProtocol, GroupCallConfig, RawCallUpdate
from .chats import ChatUpdate, GroupCallParticipant, UpdatedGroupCallParticipant
from .stream import AudioQuality, MediaStream, StreamAudioEnded, StreamVideoEnded, VideoQuality
from .update import Update

__all__ = ('AudioQuality', 'Browsers', 'Cache', 'ChatUpdate', 'Call', 'CallConfig', 'CallProtocol', 'CallData', 'RawCallUpdate', 'GroupCallConfig', 'GroupCallParticipant', 'MediaStream', 'StreamAudioEnded', 'StreamVideoEnded', 'Update', 'UpdatedGroupCallParticipant', 'VideoQuality')
