"""
This type stub file was generated by pyright.
"""

class Browsers:
    def __init__(self) -> None:
        ...
    
    @property
    def chrome_android(self): # -> str:
        ...
    
    @property
    def chrome_ios(self): # -> str:
        ...
    
    @property
    def chrome_linux(self): # -> str:
        ...
    
    @property
    def chrome_macos(self): # -> str:
        ...
    
    @property
    def chrome_windows(self): # -> str:
        ...
    
    @property
    def edge_android(self): # -> str:
        ...
    
    @property
    def edge_ios(self): # -> str:
        ...
    
    @property
    def edge_macos(self): # -> str:
        ...
    
    @property
    def edge_windows(self): # -> str:
        ...
    
    @property
    def edge_windows_mobile(self): # -> str:
        ...
    
    @property
    def edge_xbox_one(self): # -> str:
        ...
    
    @property
    def firefox_android(self): # -> str:
        ...
    
    @property
    def firefox_ios(self): # -> str:
        ...
    
    @property
    def firefox_linux(self): # -> str:
        ...
    
    @property
    def firefox_macos(self): # -> str:
        ...
    
    @property
    def firefox_windows(self): # -> str:
        ...
    
    @property
    def opera_android(self): # -> str:
        ...
    
    @property
    def opera_linux(self): # -> str:
        ...
    
    @property
    def opera_macos(self): # -> str:
        ...
    
    @property
    def opera_windows(self): # -> str:
        ...
    
    @property
    def safari_ios(self): # -> str:
        ...
    
    @property
    def safari_macos(self): # -> str:
        ...
    


