"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from time import time
from typing import Any, Optional

@dataclass
class CacheEntry:
    time: int
    expiry_time: int
    data: Any
    ...


class Cache:
    def __init__(self) -> None:
        ...
    
    def get(self, chat_id: int): # -> Any | None:
        ...
    
    def put(self, chat_id: int, data: Any, expiry_time: int = ...) -> None:
        ...
    
    @property
    def keys(self): # -> list[int]:
        ...
    
    def pop(self, chat_id: int) -> Optional[Any]:
        ...
    


