"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Union

class PyObject:
    @staticmethod
    def default(obj) -> Union[str, Dict[str, str], List[Any]]:
        ...
    
    def __str__(self) -> str:
        ...
    


