"""
This type stub file was generated by pyright.
"""

from typing import List, Optional

class AgentInfo:
    def __init__(self, name: str, version: str, device: Optional[str] = ..., os_name: Optional[str] = ..., arch_type: Optional[str] = ...) -> None:
        ...
    


class UserAgent:
    def __init__(self, user_agents: List[AgentInfo]) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


