"""
This type stub file was generated by pyright.
"""

from ...statictypes import statictypes
from ..py_object import PyObject

class AudioParameters(PyObject):
    @statictypes
    def __init__(self, bitrate: int = ..., channels: int = ...) -> None:
        ...
    


