"""
This type stub file was generated by pyright.
"""

from ntgcalls import InputMode
from ...statictypes import statictypes
from .video_parameters import VideoParameters

class VideoStream:
    @statictypes
    def __init__(self, input_mode: InputMode, path: str, parameters: VideoParameters = ...) -> None:
        ...
    


