"""
This type stub file was generated by pyright.
"""

from typing import Union
from ...mtproto_required import mtproto_required
from ...scaffold import Scaffold
from ...statictypes import statictypes

class ChangeVolumeCall(Scaffold):
    @statictypes
    @mtproto_required
    async def change_volume_call(self, chat_id: Union[int, str], volume: int): # -> None:
        ...
    


