"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Union
from ...mtproto_required import mtproto_required
from ...scaffold import Scaffold
from ...statictypes import statictypes
from ...types.chats import GroupCallParticipant

class GetParticipants(Scaffold):
    @statictypes
    @mtproto_required
    async def get_participants(self, chat_id: Union[int, str]) -> Optional[List[GroupCallParticipant]]:
        ...
    


