"""
This type stub file was generated by pyright.
"""

from typing import Union
from ...mtproto_required import mtproto_required
from ...mutex import mutex
from ...scaffold import Scaffold
from ...statictypes import statictypes

class LeaveCall(Scaffold):
    @mutex
    @statictypes
    @mtproto_required
    async def leave_call(self, chat_id: Union[int, str]): # -> None:
        ...
    


