"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, NamedTuple, Optional

class Callback(NamedTuple):
    func: Callable
    filters: Optional[Any]
    ...


class HandlersHolder:
    def __init__(self) -> None:
        ...
    
    async def propagate(self, update, client=...): # -> None:
        ...
    
    def add_handler(self, func: Callable, filters=...) -> Callable:
        ...
    
    def remove_handler(self, func: Callable): # -> None:
        ...
    


