"""
This type stub file was generated by pyright.
"""

class DeviceInfo:
    def __init__(self, identifier: str, title: str) -> None:
        ...
    
    def build_ffmpeg_command(self): # -> str:
        ...
    


