"""
This type stub file was generated by pyright.
"""

from ..types.list import List

class MediaDevices:
    @staticmethod
    async def get_screen_devices() -> List:
        ...
    
    @staticmethod
    async def get_audio_devices() -> List:
        ...
    


