"""
This type stub file was generated by pyright.
"""

from ..types.py_object import PyObject

class ScreenInfo(PyObject):
    def __init__(self, x: int, y: int, width: int, height: int, is_primary: bool, title: str) -> None:
        ...
    
    def build_ffmpeg_command(self, frame_rate: int): # -> str:
        ...
    


