"""
This type stub file was generated by pyright.
"""

class Environment:
    def __init__(self, min_pyrogram_version: str, min_telethon_version: str, min_hydrogram_version: str, client_name: str) -> None:
        ...
    
    def check_environment(self): # -> None:
        ...
    


