"""
This type stub file was generated by pyright.
"""

class TooOldPyrogramVersion(Exception):
    def __init__(self, version_needed: str, pyrogram_version: str) -> None:
        ...
    


class TooOldTelethonVersion(Exception):
    def __init__(self, version_needed: str, telethon_version: str) -> None:
        ...
    


class TooOldHydrogramVersion(Exception):
    def __init__(self, version_needed: str, hydrogram_version: str) -> None:
        ...
    


class InvalidStreamMode(Exception):
    def __init__(self) -> None:
        ...
    


class NoMTProtoClientSet(Exception):
    def __init__(self) -> None:
        ...
    


class NoActiveGroupCall(Exception):
    def __init__(self) -> None:
        ...
    


class TimedOutAnswer(Exception):
    def __init__(self) -> None:
        ...
    


class CallDeclined(Exception):
    def __init__(self, user_id: int) -> None:
        ...
    


class CallDiscarded(Exception):
    def __init__(self, user_id: int) -> None:
        ...
    


class NotInCallError(Exception):
    def __init__(self) -> None:
        ...
    


class AlreadyJoinedError(Exception):
    def __init__(self) -> None:
        ...
    


class ClientNotStarted(Exception):
    def __init__(self) -> None:
        ...
    


class PyTgCallsAlreadyRunning(Exception):
    def __init__(self) -> None:
        ...
    


class TooManyCustomApiDecorators(Exception):
    def __init__(self) -> None:
        ...
    


class GroupCallNotFound(Exception):
    def __init__(self, chat_id: int) -> None:
        ...
    


class InvalidMTProtoClient(Exception):
    def __init__(self) -> None:
        ...
    


class NoVideoSourceFound(Exception):
    def __init__(self, path: str) -> None:
        ...
    


class InvalidVideoProportion(Exception):
    def __init__(self, message: str) -> None:
        ...
    


class NoAudioSourceFound(Exception):
    def __init__(self, path: str) -> None:
        ...
    


class ImageSourceFound(Exception):
    def __init__(self, path: str) -> None:
        ...
    


class LiveStreamFound(Exception):
    def __init__(self, path: str) -> None:
        ...
    


class YtDlpError(Exception):
    def __init__(self, message: str) -> None:
        ...
    


class UnMuteNeeded(Exception):
    def __init__(self) -> None:
        ...
    


class MTProtoClientNotConnected(Exception):
    def __init__(self) -> None:
        ...
    


