"""
This type stub file was generated by pyright.
"""

from typing import Union
from .handlers import HandlersHolder

class Scaffold(HandlersHolder):
    _REQUIRED_PYROGRAM_VERSION = ...
    _REQUIRED_TELETHON_VERSION = ...
    _REQUIRED_HYDROGRAM_VERSION = ...
    def __init__(self) -> None:
        ...
    
    async def resolve_chat_id(self, chat_id: Union[int, str]): # -> None:
        ...
    
    async def start(self): # -> None:
        ...
    
    def on_update(self, filters=...): # -> None:
        ...
    


