"""
This type stub file was generated by pyright.
"""

from typing import Optional, Tuple
from .types.raw import VideoParameters

py_logger = ...
class YtDlp:
    YOUTUBE_REGX = ...
    @staticmethod
    def is_valid(link: str) -> bool:
        ...
    
    @staticmethod
    async def extract(link: Optional[str], video_parameters: VideoParameters, add_commands: Optional[str]) -> Tuple[Optional[str], Optional[str]]:
        ...
    


