"""
This type stub file was generated by pyright.
"""

from ...types.py_object import PyObject
from ..flag import Flag

class GroupCallParticipant(PyObject):
    class Action(Flag):
        JOINED = ...
        LEFT = ...
        UPDATED = ...
    
    
    def __init__(self, user_id: int, muted: bool, muted_by_admin: bool, video: bool, screen_sharing: bool, video_camera: bool, raised_hand: bool, volume: int, joined: bool, left: bool) -> None:
        ...
    


