"""
This type stub file was generated by pyright.
"""

from ..chats import GroupCallParticipant
from ..update import Update

class UpdatedGroupCallParticipant(Update):
    def __init__(self, chat_id: int, participant: GroupCallParticipant) -> None:
        ...
    


