"""
This type stub file was generated by pyright.
"""

from typing import Callable

class CustomApi:
    def __init__(self, port: int = ...) -> None:
        ...
    
    def on_update_custom_api(self) -> Callable:
        ...
    
    async def start(self): # -> None:
        ...
    


