"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, List, Optional
from ntgcalls import Protocol
from ..types.chats import GroupCallParticipant

class MtProtoClient:
    def __init__(self, cache_duration: int, client: Any) -> None:
        ...
    
    async def get_group_call_participants(self, chat_id: int) -> Optional[List[GroupCallParticipant]]:
        ...
    
    async def join_group_call(self, chat_id: int, json_join: str, invite_hash: str, have_video: bool, join_as: Any) -> str:
        ...
    
    async def request_call(self, user_id: int, g_a_hash: bytes, protocol: Protocol): # -> None:
        ...
    
    async def accept_call(self, user_id: int, g_b: bytes, protocol: Protocol): # -> None:
        ...
    
    async def discard_call(self, user_id: int): # -> None:
        ...
    
    async def confirm_call(self, user_id: int, g_a: bytes, key_fingerprint: int, protocol: Protocol): # -> None:
        ...
    
    async def send_signaling(self, user_id: int, data: bytes): # -> None:
        ...
    
    async def get_dhc(self): # -> None:
        ...
    
    async def create_group_call(self, chat_id: int): # -> None:
        ...
    
    async def leave_group_call(self, chat_id: int): # -> None:
        ...
    
    async def change_volume(self, chat_id: int, volume: int, participant: Any): # -> None:
        ...
    
    async def set_call_status(self, chat_id: int, muted_status: Optional[bool], paused_status: Optional[bool], stopped_status: Optional[bool], participant: Any): # -> None:
        ...
    
    async def get_full_chat(self, chat_id: int): # -> None:
        ...
    
    async def resolve_peer(self, user_id: int): # -> None:
        ...
    
    async def get_id(self) -> int:
        ...
    
    @property
    def is_connected(self) -> bool:
        ...
    
    @property
    def no_updates(self) -> bool:
        ...
    
    @property
    def mtproto_client(self): # -> BridgedClient:
        ...
    
    async def start(self): # -> None:
        ...
    
    def on_update(self) -> Callable:
        ...
    


