"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from ntgcalls import RTCServer

class CallProtocol:
    def __init__(self, library_versions: List[str], p2p_allowed: Optional[bool] = ..., rtc_servers: Optional[List[RTCServer]] = ...) -> None:
        ...
    


