"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Any, Optional

class CallData:
    def __init__(self, dhc_config: Any, loop: asyncio.AbstractEventLoop, g_a_hash: Optional[bytes] = ...) -> None:
        ...
    


