"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

class GroupCallConfig:
    def __init__(self, invite_hash: Optional[str] = ..., join_as: Any = ..., auto_start: bool = ...) -> None:
        ...
    


